=== thurask/thurask.github.io/dtd/repo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT repo (release*)>
<!ELEMENT release (trueos,os,radio,software,notes)>
<!ELEMENT trueos (#PCDATA)>
<!ELEMENT os (#PCDATA)>
<!ELEMENT radio (#PCDATA)>
<!ELEMENT software (#PCDATA)>
<!ELEMENT notes (#PCDATA)>

<!--
===REPO===
A list of all the OSs available on BlackBerry's public servers. Either on CSE prod or Developer (for autoloaders)

OS Format:
<release>
    <trueos>Blank, OS version if it doesn't sort properly</trueos>
    <os>OS version, OS version with leading zero(es) if it doesn't sort properly</os>
    <radio>Radio version</radio>
    <software>Software version</software>
    <notes>OS notes, generally who released it/if it's an autoloader</notes>
</release>-->

=== thurask/thurask.github.io/repo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE repo SYSTEM "dtd/repo.dtd" >
<repo>
	<release>
		<series>10.3.1</series>
		<trueos></trueos>
		<os>10.3.1.2072</os>
		<radio>10.3.1.2073</radio>
		<software>10.3.1.1450</software>
		<notes>Rogers Classic</notes>
	</release>
	<release>
		<series>10.3.1</series>
		<trueos></trueos>
		<os>10.3.1.1298</os>
		<radio>10.3.1.1299</radio>
		<software>10.3.1.841</software>
		<notes>ATT Classic</notes>
	</release>
	<release>
		<series>10.3.1</series>
		<trueos></trueos>
		<os>10.3.1.1154</os>
		<radio>10.3.1.1155</radio>
		<software>10.3.1.747</software>
		<notes>Classic</notes>
	</release>
	<release>
		<series>10.3.1</series>
		<trueos>10.3.1.997</trueos>
		<os>10.3.1.0997</os>
		<radio>10.3.1.996</radio>
		<software>N/A</software>
		<notes>SDK Autoloader</notes>
	</release>
	<release>
		<series>10.3.1</series>
		<trueos>10.3.1.634</trueos>
		<os>10.3.1.0634</os>
		<radio>10.3.1.633</radio>
		<software>N/A</software>
		<notes>SDK Autoloader</notes>
	</release>
	<release>
		<series>10.3.0</series>
		<trueos></trueos>
		<os>10.3.0.1418</os>
		<radio>10.3.0.1419</radio>
		<software>10.3.0.908</software>
		<notes>Passport</notes>
	</release>
	<release>
		<series>10.3.0</series>
		<trueos></trueos>
		<os>10.3.0.1172</os>
		<radio>10.3.0.1155</radio>
		<software>10.3.0.754</software>
		<notes>Indian Passport</notes>
	</release>
	<release>
		<series>10.3.0</series>
		<trueos></trueos>
		<os>10.3.0.1154</os>
		<radio>10.3.0.1155</radio>
		<software>10.3.0.738</software>
		<notes>Passport</notes>
	</release>
	<release>
		<series>10.3.0</series>
		<trueos></trueos>
		<os>10.3.0.1052</os>
		<radio>10.3.0.1053</radio>
		<software>10.3.0.675</software>
		<notes>Passport</notes>
	</release>
	<release>
		<series>10.3.0</series>
		<trueos>10.3.0.700</trueos>
		<os>10.3.0.0700</os>
		<radio>10.3.0.699</radio>
		<software>N/A</software>
		<notes>SDK Autoloader</notes>
	</release>
	<release>
		<series>10.3.0</series>
		<trueos>10.3.0.442</trueos>
		<os>10.3.0.0442</os>
		<radio>10.3.0.441</radio>
		<software>N/A</software>
		<notes>SDK Autoloader</notes>
	</release>
	<release>
		<series>10.2.2</series>
		<trueos></trueos>
		<os>10.2.2.1609</os>
		<radio>10.2.2.1532</radio>
		<software>10.2.2.984</software>
		<notes>SecuSmart</notes>
	</release>
	<release>
		<series>10.2.2</series>
		<trueos></trueos>
		<os>10.2.2.1531</os>
		<radio>10.2.2.1532</radio>
		<software>10.2.2.932</software>
		<notes>SecuSmart</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.3442</os>
		<radio>10.2.1.3140</radio>
		<software>10.2.1.3062</software>
		<notes>10.2.1.3247 bugfix</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.3412</os>
		<radio>10.2.1.3140</radio>
		<software>10.2.1.3054</software>
		<notes>10.2.1.3247 bugfix, Z3</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.3358</os>
		<radio>10.2.1.3359</radio>
		<software>10.2.1.3023</software>
		<notes>10.2.1.3253 bugfix, Sprint Q10 -- No STL100-1</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.3337</os>
		<radio>10.2.1.3338</radio>
		<software>10.2.1.3014</software>
		<notes>ATT</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.3289</os>
		<radio>10.2.1.3290</radio>
		<software>10.2.1.2991</software>
		<notes>VZW Z30 -- No STL100-1</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.3253</os>
		<radio>10.2.1.3182</radio>
		<software>10.2.1.2976</software>
		<notes>10.2.1.3181 bugfix, VZW Z10/Q10</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.3247</os>
		<radio>10.2.1.3140</radio>
		<software>10.2.1.2977</software>
		<notes>10.2.1.3175 bugfix</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.3175</os>
		<radio>10.2.1.3140</radio>
		<software>10.2.1.2941</software>
		<notes>10.2.1 MR MR</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.2947</os>
		<radio>10.2.1.2948</radio>
		<software>10.2.1.2788</software>
		<notes>Z3 -- Z3 radio</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.2758</os>
		<radio>10.2.1.2759</radio>
		<software>10.2.1.2674</software>
		<notes>Sprint Q10</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.2294</os>
		<radio>10.2.1.2142</radio>
		<software>10.2.1.2192</software>
		<notes>10.2.1.2141 bugfix -- No STL100-1</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.2273</os>
		<radio>10.2.1.2274</radio>
		<software>10.2.1.2179</software>
		<notes>ATT</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.2234</os>
		<radio>10.2.1.2235</radio>
		<software>10.2.1.2160</software>
		<notes>ShopBlackBerry</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.2228</os>
		<radio>10.2.1.2229</radio>
		<software>10.2.1.2156</software>
		<notes>T-Mobile</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.2180</os>
		<radio>10.2.1.2181</radio>
		<software>10.2.1.2126</software>
		<notes>VZW Z30 -- Z10/Z30/Q10</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.2174</os>
		<radio>10.2.1.2175</radio>
		<software>10.2.1.2122</software>
		<notes>VZW Z10/Q10</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.2141</os>
		<radio>10.2.1.2142</radio>
		<software>10.2.1.2102</software>
		<notes>10.2.1 MR</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.1927</os>
		<radio>10.2.1.1926</radio>
		<software>N/A</software>
		<notes>SDK Autoloader</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.1925</os>
		<radio>10.2.1.1899</radio>
		<software>10.2.1.537</software>
		<notes>10.2.1</notes>
	</release>
	<release>
		<series>10.2.1</series>
		<trueos></trueos>
		<os>10.2.1.1057</os>
		<radio>10.2.1.1056</radio>
		<software>N/A</software>
		<notes>SDK Autoloader</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1809</os>
		<radio>10.2.0.1810</radio>
		<software>10.2.0.431</software>
		<notes>Cosmote Greece</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1803</os>
		<radio>10.2.0.1804</radio>
		<software>10.2.0.429</software>
		<notes>10.2.0 MR</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1793</os>
		<radio>10.2.0.1792</radio>
		<software>N/A</software>
		<notes>SDK Autoloader</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1791</os>
		<radio>10.2.0.1792</radio>
		<software>10.2.0.424</software>
		<notes>10.2.0</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1767</os>
		<radio>10.2.0.1768</radio>
		<software>10.2.0.415</software>
		<notes>10.2.0</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1761</os>
		<radio>10.2.0.1762</radio>
		<software>10.2.0.413</software>
		<notes>10.2.0</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1725</os>
		<radio>10.2.0.1726</radio>
		<software>10.2.0.405</software>
		<notes>Servers</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1521</os>
		<radio>10.2.0.1522</radio>
		<software>10.2.0.224</software>
		<notes>Z30</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1445</os>
		<radio>10.2.0.1444</radio>
		<software>N/A</software>
		<notes>SDK Autoloader</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1443</os>
		<radio>10.2.0.1444</radio>
		<software>10.2.0.210</software>
		<notes>Z30</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1233</os>
		<radio>10.2.0.1234</radio>
		<software>10.2.0.262</software>
		<notes>VZW Z30</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos></trueos>
		<os>10.2.0.1157</os>
		<radio>10.2.0.1156</radio>
		<software>N/A</software>
		<notes>SDK Autoloader</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos>10.2.0.783</trueos>
		<os>10.2.0.0783</os>
		<radio>10.2.0.784</radio>
		<software>10.2.0.110</software>
		<notes>Servers</notes>
	</release>
	<release>
		<series>10.2.0</series>
		<trueos>10.2.0.341</trueos>
		<os>10.2.0.0341</os>
		<radio>10.2.0.340</radio>
		<software>N/A</software>
		<notes>SDK Autoloader</notes>
	</release>
	<release>
		<series>10.1</series>
		<trueos></trueos>
		<os>10.1.0.4828</os>
		<radio>10.1.0.4829</radio>
		<software>10.1.0.4211</software>
		<notes>Sprint Q10</notes>
	</release>
	<release>
		<series>10.1</series>
		<trueos></trueos>
		<os>10.1.0.4780</os>
		<radio>10.1.0.4781</radio>
		<software>10.1.0.4200</software>
		<notes>T-Mobile</notes>
	</release>
	<release>
		<series>10.1</series>
		<trueos></trueos>
		<os>10.1.0.4699</os>
		<radio>10.1.0.4700</radio>
		<software>10.1.0.4189</software>
		<notes>VZW Q10</notes>
	</release>
	<release>
		<series>10.1</series>
		<trueos></trueos>
		<os>10.1.0.4651</os>
		<radio>10.1.0.4652</radio>
		<software>10.1.0.4184</software>
		<notes>10.1 MR</notes>
	</release>
	<release>
		<series>10.1</series>
